# -*- coding: utf-8 -*-
"""Task-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIZWlXef2rJHji6rHSFPhgrvlT1rzdwg
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('housing_price_dataset.csv')

print("Basic Dataset Structure: \n",df.head(),"\n")

print("Missing Values check (data cleaning):\n",df.isnull().sum(),"\n")

df = df.dropna()
print("Basic Statistical inferences: \n",df.describe(),"\n")

corr_matrix = df[['SquareFeet', 'Bedrooms', 'Bathrooms', 'Price']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

X = df[['SquareFeet', 'Bedrooms', 'Bathrooms']]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print()
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2} \n')

plt.scatter(y_test, y_pred)
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('Actual vs Predicted Prices')
plt.show()